// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package spring.security.starter.model;

import org.springframework.beans.factory.annotation.Configurable;
import spring.security.starter.model.Todo;

privileged aspect Todo_Roo_Configurable {
    
    declare @type: Todo: @Configurable;
    
}
